Fix overflow / timing
Waaaaay too fast. also, I think that 255 was overflowing the code.

raceback (most recent call last):
  File "sunrise.py", line 113, in <module>

matrix.Fill(sunrise_lw.color[0],sunrise_lw.color[1],sunrise_lw.color[2])
  File "rgbmatrix/core.pyx", line 58, in rgbmatrix.core.RGBMatrix.Fill
(rgbmatrix/core.cpp:1858)
OverflowError: value too large to convert to uint8_t